library(shiny)
library(leaflet)
library(dplyr)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggplot2)

# Read your dataset
df <- read.csv("C:/Jürgen/Studium/Data-Driven Decision Support/DashboardProject/DDDS_Energy_Dashboard/ddds_energy_consumption_v1.0/df_countries_preprocessed.csv")

# Load the world shapefile
world <- ne_countries(scale = "medium", returnclass = "sf")

# Manually correct the ISO codes for France and Norway
world$iso_a3[world$name == "France"] <- "FRA"
world$iso_a3[world$name == "Norway"] <- "NOR"

# Verify the changes (Optional: print to check)
print(world %>% filter(name %in% c("France", "Norway")) %>% select(name, iso_a3))

# Define a mapping from variable names to more descriptive titles
variable_titles <- c(
  "population" = "Population",
  "gdp" = "GDP",
  "electricity_demand" = "Electricity Demand TWh",
  "electricity_generation" = "Electricity Generation TWh",
  "per_capita_electricity" = "Electricity Generation per Capita KWh/Person",
  "energy_per_capita" = "Energy Consumption per Capita KWh/Person",
  "renewables_elec_per_capita" = "Electricity Generation from Renewables per Capita KWh/Person",
  "renewables_energy_per_capita" = "Electricity Consumption from Renewables per Capita KWh/Person",
  "renewables_share_elec" = "Share Renewables Generation %",
  "renewables_share_energy" = "Share Renewables Consumption %",
  "biofuel_share_elec" = "Share of electricity generated by bioenergy",
  "coal_share_elec" = "Share of electricity generated by coal",
  "fossil_share_elec" = "Share of electricity generated by fossil fuels",
  "gas_share_elec" = "Share of electricity generated by gas",
  "nuclear_share_elec" = "Share of electricity generated by nuclear power",
  "solar_share_elec" = "Share of electricity generated by solar power",
  "wind_share_elec" = "Share of electricity generated by wind power"
  
)

# Define UI
ui <- fluidPage(
  titlePanel(
    uiOutput("mainTitle")
  ),
  sidebarLayout(
    sidebarPanel(
      selectInput("variable", "Variable to display:", choices = setNames(names(variable_titles), variable_titles), selected = "renewables_share_elec"),
      sliderInput("year", "Year:", min = min(df$year), max = max(df$year), 
                  value = max(df$year), step = 1, animate = animationOptions(interval = 1000, loop = TRUE)),
      sliderInput("yearRange", "Year Range:", min = min(df$year), max = max(df$year), 
                  value = c(min(df$year), max(df$year)), step = 1),
      selectInput("scatter_var", "Second Variable for Scatter Plot:", choices = setNames(names(variable_titles), variable_titles)),
      selectInput("size_var", "Variable for Point Size in Scatter Plot:", choices = setNames(names(variable_titles), variable_titles)),
      actionButton("reset", "Reset Line Chart"),
      actionButton("reset_scatter", "Reset Scatter Plot")
    ),
    mainPanel(
      fluidRow(
        column(6, leafletOutput("map", height = "500px")),
        column(6, plotOutput("scatterPlot", height = "500px"))
      ),
      fluidRow(
        column(12, plotOutput("lineChart", height = "400px"))
      )
    )
  )
)

# Define server logic
server <- function(input, output, session) {
  selected_countries <- reactiveVal(character())
  selected_scatter_countries <- reactiveVal(character())
  
  filtered_data <- reactive({
    df %>% filter(year == input$year)
  })
  
  merged_data <- reactive({
    left_join(world, filtered_data(), by = c("iso_a3" = "iso_code"))
  })
  
  observe({
    print(head(filtered_data()))  # Print filtered data for debugging
    print(head(merged_data()))  # Print merged data for debugging
  })
  
  map_view <- reactiveValues(zoom = NULL, center = NULL)
  
  observe({
    input$year
    isolate({
      if (!is.null(input$map_bounds)) {
        map_view$zoom <- input$map_zoom
        map_view$center <- input$map_center
      }
    })
  })
  
  output$map <- renderLeaflet({
    data <- merged_data()  # Evaluate reactive expression
    pal <- colorNumeric(palette = "RdYlGn", domain = data[[input$variable]])
    
    map <- leaflet(data = data) %>%
      addTiles() %>%
      addPolygons(
        fillColor = ~pal(data[[input$variable]]),
        weight = 1,
        opacity = 1,
        color = 'white',
        dashArray = '3',
        fillOpacity = 0.7,
        highlightOptions = highlightOptions(
          weight = 2,
          color = "#666",
          dashArray = "",
          fillOpacity = 0.7,
          bringToFront = TRUE
        ),
        label = ~paste(name, formatC(data[[input$variable]], format = "f", big.mark = ",")),
        labelOptions = labelOptions(
          style = list("font-weight" = "normal", padding = "3px 8px"),
          textsize = "15px",
          direction = "auto"
        ),
        layerId = ~iso_a3
      ) %>%
      addLegend(pal = pal, values = data[[input$variable]], opacity = 0.7, title = NULL,
                position = "bottomright")
    
    if (!is.null(map_view$zoom) && !is.null(map_view$center)) {
      map <- setView(map, lng = map_view$center$lng, lat = map_view$center$lat, zoom = map_view$zoom)
    }
    
    map
  })
  
  observeEvent(input$map_shape_click, {
    click <- input$map_shape_click
    if (!is.null(click$id)) {
      selected <- selected_countries()
      if (click$id %in% selected) {
        selected <- selected[selected != click$id]
      } else {
        selected <- c(selected, click$id)
      }
      selected_countries(selected)
      selected_scatter_countries(selected)  # Update scatter plot selection
    }
  })
  
  observeEvent(input$reset, {
    selected_countries(character())
  })
  
  observeEvent(input$reset_scatter, {
    selected_scatter_countries(character())
  })
  
  output$lineChart <- renderPlot({
    req(selected_countries())
    req(input$yearRange)
    
    line_data <- df %>%
      filter(iso_code %in% selected_countries(), year >= input$yearRange[1], year <= input$yearRange[2]) %>%
      select(year, country, variable = input$variable)
    
    ggplot(line_data, aes(x = year, y = variable, color = country, group = country)) +
      geom_line(size = 1.2) +
      labs(title = paste("Trend of", variable_titles[[input$variable]]), x = "Year", y = variable_titles[[input$variable]]) +
      theme_minimal(base_size = 15) +
      theme(plot.title = element_text(hjust = 0.5))
  })
  
  output$scatterPlot <- renderPlot({
    req(selected_scatter_countries())
    req(input$year)
    
    scatter_data <- df %>%
      filter(iso_code %in% selected_scatter_countries(), year == input$year) %>%
      select(country, x_var = input$variable, y_var = input$scatter_var, size_var = input$size_var)
    
    ggplot(scatter_data, aes(x = x_var, y = y_var, color = country, size = size_var)) +
      geom_point() +
      scale_size(range = c(2, 10)) +
      labs(title = paste("Scatter Plot of", variable_titles[[input$variable]], "vs", variable_titles[[input$scatter_var]]), 
           x = variable_titles[[input$variable]], y = variable_titles[[input$scatter_var]], size = variable_titles[[input$size_var]]) +
      theme_minimal(base_size = 15)
  })
  
  output$mainTitle <- renderUI({
    title <- paste("Renewable Energy Consumption Dashboard   --   ", variable_titles[[input$variable]], "in", input$year)
    h2(title, align = "center")
  })
}

# Run the app
shinyApp(ui, server)
